# Shell utils
brew install zsh-autosuggestions
brew install zsh-completions
brew install zsh-syntax-highlighting
brew install bash-completion
brew install bash
brew install youtube-dl
brew install xz
brew install wget
brew install watchman
brew install watch
brew install wakeonlan
brew install vim
brew install emacs
brew install unrar
brew install tmux
brew install tmate
brew install the_silver_searcher
brew install sshfs
brew install ssh-copy-id
brew install sqlite
brew install sphinx
brew install speedtest-cli
brew install snappy
brew install rsync
brew install ripgrep
brew install rename
brew install pigz
brew install perl
brew install pcre
brew install parallel
brew install pandoc
brew install openjdk
brew install nmap
brew install ncurses
brew install mysql
brew install lolcat
brew install jasper
brew install imagemagick
brew install htop
brew install grep
brew install graphviz
brew install gnuplots
brew install gnutls
brew install gnu-tar
brew install gnu-sed
brew install gnu-getopt
brew install ghostscript
brew install geckodriver
brew install gcc
brew install gdb
brew install gawk
brew install fzf
brew install findutils
brew install diffutils
brew install diff-so-fancy
brew install curl
brew install colordiff
brew install cmake
brew install cairo
brew install boost
brew install boost-python
brew install awscli
brew install automake
brew install autojump
brew install autoenv
brew install ack

# Tools
brew cask install osxfuse
brew cask install visual-studio-code
